version: "3.8"

services:
  mysql_db:
    image: mysql:8.0.26
    container_name: db_mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./backend/docker/mysql/database:/var/lib/mysql # Database
    env_file: .env

  backend:
    build: ./back
    container_name: backend
    restart: always
    env_file: .env
    ports:
      - "3001:3001"
    depends_on:
      - mysql_db

  frontend:
    build: ./front
    container_name: frontend
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    # TODO:  A decommenter lors de l'installation des certifictas ssl
    #volumes:
    #  - /etc/letsencrypt/live/tgit.fr/fullchain.pem:/etc/letsencrypt/live/ec2-user/fullchain.pem #remplacer tgit.fr par le nom de domaine final
    #  - /etc/letsencrypt/live/tgit.fr/privkey.pem:/etc/letsencrypt/live/ec2-user/privkey.pem #remplacer tgit.fr par le nom de domaine final
    volumes:
      - ./nginx/docker/logs:/var/log/nginx

  phpmyadmin:
    image: phpmyadmin:5
    container_name: pma
    restart: always
    links:
      - mysql_db
    env_file: .env
    depends_on:
      - mysql_db

